### ISSUE TITLE
Docs: Update derivation examples to use new-style `derive: using`

### ISSUE THREAD

**Issue by jshearer** [estuary/flow#1113]
A customer in the public Slack very reasonably got confused because using `flowctl typescript generate` on their derivation written like this wasn't working:

```
collections:
  acme/derivation/x:
    key:
      - /ID
    derivation:
      transform:
        x:
          source:
            name: acme/source/x/new
          shuffle:
            key:
              - /ID
          publish:
            lambda: typescript
        y:
          source:
            name: acme/source/x/old
          shuffle:
            key:
              - /ID
          publish:
            lambda: typescript
      typescript:
        module: acme.ts
```

Our docs talk about `flowctl typescript generate`:
- [Here](https://docs.estuary.dev/concepts/flowctl/#typescript-code-generation)
- [Here](https://docs.estuary.dev/guides/flowctl/create-derivation/#using-local-terminal)

Our examples have quite a few examples of typescript derivations using the old style `derivation: {transform: {publish: {lambda: typescript}}}`:
- [Here](https://github.com/estuary/flow/blob/master/examples/derive-patterns/summer.flow.yaml#L17)
- [Here](https://github.com/estuary/flow/blob/master/examples/derive-patterns/join-inner.flow.yaml#L12)
- [Here](https://github.com/estuary/flow/blob/master/examples/net-trace/services.flow.yaml#L21)
etc.

It looks like the docs themselves have been updated to use the new `derive: using` style so I don't think there's anything to change there, though I didn't look at every page.
