### ISSUE TITLE
Build should error when the top level collection schema is not `type: object`

### ISSUE THREAD

**Issue by psFried** [estuary/flow#127]
This example currently builds successfully:

```
collections:
  foo:
    schema: {type: string}
    key: ['']
```

This ought to be a build error, since the top level of the schema must be an object in order to be able to inject the `_meta` property. Currently, ingesting a record to this collection will cause flow-ingester to panic.
