### ISSUE TITLE
models: support arbitrary prefixes and suffixes for table names in `targetNaming`

### ISSUE THREAD

**Issue by psFried** [estuary/flow#2234]
The original ask from @dyaffe was to support something like:

```
source:
  targetNaming:
    prefix: 'some_prefix_'
    suffix: '_some_suffix'
```

which given the collection `acmeCo/foo/bar` would result in table names like `some_prefix_bar_some_suffix`. I'm currently thinking that perhaps we should represent it as a `nameTemplate: 'some_prefix_{{name}}_some_suffix'`, because then it would allow the template to also reference the full collection name or the "schema" component. Then the question is whether we should also support a `schemaTemplate` for connectors that use `x-schema-name`. We should probably settle on a design before we proceed.
