### ISSUE TITLE
inference: missing implicit projections for collection key within `additionalItems` array

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#231]
When using a schema that composes `additionalItems` and `minItems`, where the collection key references an index < minItems, we fail to generate a projection for the collection's key. This fails later, during validation of the CollectionSpec.

For example given collection schema:
```yaml
type: object
properties:
  arr:
    type: array
    additionalItems: {type: integer}
    minItems: 2
required: [arr]
```
And collection key `[/arr/1]`, we (correctly) allow the collection key because we infer its required existence and type.
But we don't create an implicit projection having this location. Currently, downstream bits (and the Go `flow.CollectionSpec` implementation) require that it do exist (and it seems pretty reasonable that it would).
