### ISSUE TITLE
Rename airbyteSource

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#292]
We have a connector type of "airbyteSource" which only makes sense internally.  To anyone external, it seems like we're using a connector that was created by Airbyte.  We should update the name to be more descriptive to something like:

- airbyteSpec
- airbyteWrapper
- airbyteProtocol
- openConnector

**Comment by willdonnelly** [comment]
Just throwing out another option, what about `imageSource`? To me the most relevant fact is that this is asking Flow to run a Docker image, as opposed to a hypothetical gRPC source in the future.

**Comment by dyaffe** [comment]
I like that a lot actually

**Comment by jgraettinger** [comment]
Perhaps just `connector`  ?

Specifically we'd define a `connector` as a type of endpoint that takes a docker image and a configuration, where the configuration is provided either as a relative file or inline, like:

```yaml
captures:
  acmeCo/my-capture:
    endpoint:
      connector:
        image: the/image:version
        config:
          image: {specific: configuration}
    bindings: { ... }
    
materializations:
  acmeCo/my-materialization:
    endpoint:
      connector:
        image: the/image:version
        config: path/to/config.yaml
    bindings: { ... }
```

Other types of endpoints:
 * A capture may also be an `ingest` instead of a `connector`.
 * A materialization may also be `sqlite` instead of a `connector`.


## Protocol Versioning

How do we determine the specific protocol (and possibly its version) implemented by the connector ? Today we support Airbyte captures, but it seems natural to also support the native Flow capture spec, or other forms. Same deal with materializations, where we might talk to it over protobuf or JSON, and where we might introduce support for other protocols like airbyte destinations. Ideally this wouldn't be on the user to provide -- we ought to ask the container!

Possibly [image annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) / docker labels  would suite ? Note that airbyte applies no labels today, to my knowledge.
