### ISSUE TITLE
proposal: tight integration with `sops` for credential management

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#296]
# Overview

Mozilla [sops](https://github.com/mozilla/sops) is a tool for securing credentials that are distributed through a version control system such as Git. It's highly complementary to Flow's evolving control plane architecture, and I propose that we standardize on `sops` for all of:

1) The specific tool used for automated unwrapping of credentials in started connector invocations, within the managed Flow runtime.
2) A blessed, opinionated strategy for management of credentials in user GitOps Flow catalogs
3) The tool used within the control plane to separate and protect user credentials provided through UI-based workflows.

This is an incremental step towards the full workflow discussed in #278, that appears cheap in implementation effort but high leverage, as we're internally feeling the pain right now re: 2) above. Looking forward sops's design introduces some neat new possibilities not contemplated as part of #278, such as a bring-your-own KMS approach.

# Background

In #278 we proposed a Vault-based architecture for securing credentials within Flow's managed runtime.
We proposed a secure proxy component with which the runtime interacts through our established capture and materialization protocols, which receives a capability from the flow consumer shard to unwrap specific credentials required for a connector to function. The proxy uses this capability to unwrap the connector configuration and delegate to the connector over its chosen protocol.

This "unwrap" was to-date under specified, but essentially is a merge of a more-accessible, less sensitive configuration with a more-sensitive set of credentials. As a concrete example, a Postgres connector might have the DB hostname and user in-the-clear, while protecting the password.

Also in #278, we noted the related issue of credential management in a GitOps-maintained Flow catalog. We elected not to attempt to solve it in that design, but it remains an ongoing pain point.

One other important bit of context is to note that the managed Flow runtime runs with a specific identity (a GCP service account, an AWS IAM role, etc). Today, a user arranges for Flow to write into the user's owned buckets by configuring a storage mapping and granting access to those buckets to this managed Flow identity. This is relevant because this pre-existing identity can be further leveraged to protect and authorize decryption of connector credential materials.

# Details on `sops`

sops is a CLI tool and workflow for protecting version-controlled secrets, which seeks to:

 * Maintain document structure of configuration files as JSON or YAML, by encrypting values but not keys.
 * Provide flexibility in the composition of both encrypted and in-the-clear values within a document.
 * Provide workflow strategies which avoid secrets from ever being written to disk.
 * Support many KMS systems -- GCP, AWS, Azure, and Vault -- including secret sharing across multiple KMS's, with key rotation.
   * Integrations are through the use of "application default credentials" for each of the cloud providers (`gcloud auth` for GCP, an ~/.aws/config for AWS, etc).
 
Suppose we have a configuration document like:
```yaml
hostname: my.production.database
port: 5432
user: flow_cdc
# Password that we want to protect.
password: super-secret-value
```

As a matter of choice and convention, we'd often *like* most of this configuration to be in-the-clear so that internal browsers of our Flow catalog can introspect the configuration and understand what's happening. Suppose `password` is the only location we'd like to protect. We first rename it to `password_sops`, and then run:

```console
$ sops --encrypt --in-place --encrypted-suffix _sops --gcp-kms projects/helpful-kingdom-273219/locations/global/keyRings/johnny-testing/cryptoKeys/sops-key config.yaml
```

This initializes a sops document which is protected by the named GCP key, that looks like:
```yaml
hostname: my.production.database
port: 5432
user: flow_cdc
# Password that we want to protect.
password_sops: ENC[AES256_GCM,data:9B0ahhn18fBIYEC9CukFAsIa,iv:M4Zar17QWz6iNbH7R/umXhiKjEBZ/aCtmZWQ2jaF+L8=,tag:qK5xLGmwd6zJrJrr86d3PA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/global/keyRings/johnny-testing/cryptoKeys/sops-key
          created_at: "2021-11-21T17:20:36Z"
          enc: CiQAengdgeYQpauTPZxzQEhhbChKB3URQbErUvzjQuQUut56VZASSQB4MnWbqOsvEs7o3+30DYM3EAK8C2U8nydCaLftAcsgoDDZtiT30lgF9mtro4pq6lqrY/ouEXeRA9nrr5XHy+cMltVaOfYryck=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-21T17:20:36Z"
    mac: ENC[AES256_GCM,data:LSwiy8PDZM2QmDx9H6KNWn5hUTntmQTLvDSEal71Z9acwZqmvvlXloIuZspR4fIrs+YzQNUgzDP0dWF9fc7B4sb1Xu7CPoV78EWh0K0xJPIXl+EpRgTdVUVlgsD23HFlwb3xvkD8SOGvD4OyD5xY4DfTNjK+VWaO1/QNs/LyhzE=,iv:mHceiyYSRp9rGTUSTBv3GXhYx2VpFmAc+qk90BeG8MI=,tag:DFhV1HmL8Suzw3LZjtjRtQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.1
```

Additional things to note about this representation:

 * _Only_ the password is secured. All other fields are in-the-clear and readable.
 * The `_sops` suffix is just a convention I've used in this invocation. sops has a variety of ways to identify portions to protect vs pass-through.
 * The `sops` section is fully self describing, and includes:
   * Identification of the specific KMS keys which protect the document.
   * Encryptions of a document "master key" under each of the KMS keys. The master key is protected by KMS keys, and once decrypted can be used to decrypt protected values of the document.
   * A MAC over the entire document, which protects against reordering attacks.
   * The configured `--encrypted.suffix` convention I selected when initializing the file.

The blessed path for editing a sops file is to use `sops config.yaml`, which opens an editor on the user's behalf, and then re-encrypts on save and exit. With the exception of active edits of a configuration, decrypted representations _do not exist_ on disk.

## Bring-your-own KMS

`sops` is able to work with _lots_ of KMS's, including public cloud offerings as well as Vault. It's strategy of storing keys within the `sops` stanza means that Flow doesn't need to concern itself with the KMS being used.

The **essential requirement** is that the KMS must authorize the identified keys for use with the managed Flow identity, which we can provide to them (as a named service account or IAM identity).

If they wish to, by bringing their own KMS the user is able to a) revoke Flow access to all or some keys, or versions of keys, at any time, and b) enable their own, separate audit logging of key access for compliance or to look for anomalies.

Those access logs could further be paired with a task's own produced logs of when it's accessing key materials for discrepancies.

# Integration

## Connector Invocations

Today, CaptureSpecs and MaterializationSpecs contain an unopinionated JSON-encoded endpoint configuration that's directly passed to the connector. By convention, we'd switch to having this representation be a sops-protected document.

When preparing a connector for invocation the Flow runtime would then:

* Look for a `/sops` section in the document, and if present use `sops` to unwrap (otherwise it's passed through).
* If a `/sops/encrypted_suffix` exists, re-shape the decrypted config to remove this suffix, restoring `/password` from `/password_sops` in our example _(can we use `jq` for this?)_.
* Pass the configuration into the connector.

As a precondition, KMSs used within sops documents must allow for the Flow runtime identity (GCP service account, AWS IAM identity) to access the named keys, or this unwrap will error.

To the greatest degree possible, we'd like to minimize decrypted representations of configuration within memory and especially disk. The way in which we do this will change over time, as we introduce the secure proxy component. As a specific note, we can likely pass configs to Airbyte connectors as a mounted file pipe. This makes the config read-able just once, and keeps it off of the disk. Similarly we can shell out to `sops` and `jq` to read a decrypted blob of the configuration that we a) avoid parsing within the long-lived Flow consumer application, so we don't have extra copies floating around in its heap, and b) zero out in memory as soon as we've passed it to the connector.

## Config Files in Catalogs

Today, both captures and materializations use in-line configuration sections which carry the connector-specific endpoint details.
To use `sops` effectively, it's essentially required that these configuration documents be managed as separate files. This seems reasonably desirable even _without_ this constraint.

We'd update the `config` stanza of these connectors to allow values to be either a) an inline object, as is the case today, or b) a relative URL reference to a file which provides the configuration. The handling would be very similar to our treatment of inline-vs-external `schema` stanzas today within collections.

This allows a capture or materialization definition to reference a connector config document which is protected using the standard `sops` workflows.

## Catalog Build, Development, & Deployment Workflows

In this proposal, we'd recommend a bless `sops` for protection of secrets within GitOps catalogs.

However catalogs are often built, developed, and tested on local developer machines. These workflows perform connector invocations, either to validate a proposed specification, or to run it within a temporary local data plane. Local contexts will of course _not_ be running with the managed production Flow identity.

Fortunately, this "Just Works" (assuming the other bits of integration exist) through `sops`'s use of application default credentials. So long as the _user_ is also authorized to the KMS in question -- for example, by using `gcloud auth` to enable their personal account, which has prior access to the key -- then that capability will automatically be used instead.

We'll have to carefully think through how this would work as we continue to evolve local development practices. For example, introducing containerization of a local data plane would significantly increase the friction, as that containerized context would need to be wired up with an appropriate identity to similarly access keys.

# Future Work

This proposal is directionally in line with, but isn't a complete implementation of the #278 design:

* We still would like to introduce the secure proxy component, for additional security separation benefit, and as a delegated means of supporting multiple connector protocols that's encapsulated and separated from the Flow runtime.
* The `sops` workflow is directly relying on the configured identity of the Flow runtime -- it doesn't provide for the one-time encrypted envelope design of #278, which provides additional separation between the Flow runtime identity and KMS materials. This probably makes sense to tackle in concert with the secure proxy component.
