### ISSUE TITLE
Use `allOf` wrapping technique in compilation phase of JSONSchema

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#445]
At the moment, we support up to 64 fields at each level of a JSONSchema, however there are cases where there are more than 64 fields.

One way to work around this is to wrap `allOf` around the JSONSchema when we are compiling it for our own code's usage. We need to do this ensuring that the JSONSchema passed to the connector stays intact because the code that handles the JSONSchema is usually not 100% compatible with spec and we see this kind of code commonly:

```
if x['type'] == 'object':
  props = x['properties']
```

This fails if we modify the JSONSchema below:

```
type: object
properties:
  name:
    type: string
```

To:

```
type: object
allOf:
  - properties:
      name:
        type: string
```

So we need to do this transparently.
