### ISSUE TITLE
Allow Connectors Without Schema to Use Same Resource

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#673]
**Problem**
We currently restrict that resource names are unique when publishing a materialization.  Generally this makes sense, because they all have unique schemas.  

Some connectors don't behave that way though -- specifically pub/sub is an example of a connector that doesn't require schema and therefore can handle multiple collections that use the same resource.  

For our Google Cloud Dataflow integration, users need to create one subscription for each resource ("topic" within that system) we create and it would make the workflow 10x easier to combine multiple collections within the same topic.

**Comment by jgraettinger** [comment]
In the case of mapping multiple bindings into a single collection: would we want a wrapping "envelope" which identifies _which_ binding a particular message came from? Otherwise the user would have to figure this out for themselves and documents of multiple collections kind of get munged together.

This envelope could include a unique identifier for the binding provided by the user (say, a subtopic), which could be part of the resource spec, and then *that* would be the actual resource path returned by the connector -- which would resolve this uniqueness issue without altering the requirement that all resource paths be unique.

The subtopic could default to the string "default", so that the user doesn't have to enter them all unless they're actually using this muxing.

@williamhbaker thoughts?

**Comment by jgraettinger** [comment]
I'm inclined to say we shouldn't do this, and that, if the user wants N different collections plumbed into the same pub/sub topic, they should create a derivation which transforms the N collections by wrapping each in an envelope that identifies _which_ stream it came from. For example:

```yaml
transforms:
  - name: fromClicks
     source: my/clicks
     lambda: SELECT 'clicks' AS type, JSON($flow_document) AS event
  - name: fromConversions
     source: my/conversions
     lambda: SELECT 'conversions' AS type, JSON($flow_document) AS event
```

If it were common, we _could_ have automation to fully write this derivation on their behalf.
