### ISSUE TITLE
parser: configs don't get validated on publish

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#799]
It is possible to create a connector with a parser config that is invalid and still allows itself to be published via the CLI. The connector will immediately fail with a cryptic error message.

I encountered this when trying to configure the parser like this, which is invalid but still does publish:

```
parser:
    format:
        type: csv
        quote: '"'
```

The errors emitted from the connector are along the lines of "failed to parse object", and there's a bit of "failed to parse config: missing field `config` at line 1 column 199" as well.

The correct parser configuration is this:
```
parser:
    format:
        type: csv
        config:
            quote: '"'
```
